# Generated by Django 5.0.1 on 2024-01-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productimage_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
